/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  eta // clock
    , input  eta1 // reset
    , input  eta2 // enable

      // Outputs
    , output wire signed [63:0] result
    );
  reg signed [63:0] result_1 = 64'sd0;
  wire signed [63:0] result_2;
  // deleteWorthy/deleteme.hs:3:1-64
  wire  b;
  wire signed [63:0] x;

  // register begin
  always @(posedge eta or  posedge  eta1) begin : result_1_register
    if ( eta1) begin
      result_1 <= 64'sd0;
    end else if (eta2) begin
      result_1 <= result_2;
    end
  end
  // register end

  assign result_2 = b ? 64'sd0 : (x + 64'sd1);

  assign b = result_1 == 64'sd7;

  assign x = result_1;

  assign result = result_1;


endmodule

