/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input signed [31:0] a

      // Outputs
    , output wire signed [31:0] result_0
    , output wire signed [31:0] result_1
    );
  wire signed [31:0] result_4;
  reg signed [31:0] result_5 = 32'sd0;
  // mixed2.hs:9:1-73
  wire  b;
  wire  result_6;
  // mixed2.hs:16:5-74
  wire  b_0;
  // mixed2.hs:16:5-74
  wire signed [63:0] t;
  wire signed [63:0] result_7;
  reg signed [63:0] result_8 = 64'sd0;
  reg  result_9 = 1'b0;
  wire [63:0] result;

  assign result_4 = result_9 ? a : result_5;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_5_register
    if ( rst) begin
      result_5 <= 32'sd0;
    end else if (en) begin
      result_5 <= result_4;
    end
  end
  // register end

  assign b = result_8 == 64'sd3;

  assign result_6 = b ? 1'b1 : 1'b0;

  assign b_0 = result_8 < 64'sd3;

  assign t = result_8 + 64'sd1;

  assign result_7 = b_0 ? t : 64'sd0;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_8_register
    if ( rst) begin
      result_8 <= 64'sd0;
    end else if (en) begin
      result_8 <= result_7;
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_9_register
    if ( rst) begin
      result_9 <= 1'b0;
    end else if (en) begin
      result_9 <= result_6;
    end
  end
  // register end

  assign result = {a,   result_5};

  assign result_0 = $signed(result[63:32]);

  assign result_1 = $signed(result[31:0]);


endmodule

