/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input wire  clk // clock
    , input wire  rst // reset
    , input wire  en // enable
    , input wire signed [63:0] input0_0
    , input wire  input0_1

      // Outputs
    , output wire  result_0_0
    , output wire  result_0_1
    , output wire signed [63:0] result_0_2
    , output wire  result_0_3
    , output wire  result_0_4
    , output wire signed [63:0] result_0_5_0
    , output wire  result_0_5_1
    , output wire signed [63:0] result_0_6
    , output wire  result_0_7
    , output wire  result_0_8
    , output wire signed [63:0] result_0_9
    , output wire signed [63:0] result_0_10
    , output wire signed [63:0] result_0_11_0
    , output wire signed [63:0] result_0_11_1
    , output wire signed [63:0] result_1_0_0
    , output wire  result_1_0_1
    , output wire signed [63:0] result_1_1_0
    , output wire  result_1_1_1
    );
  wire [388:0] result_2;
  // sliding_window_high_freq.hs:293:1-102
  wire  eta;
  // sliding_window_high_freq.hs:293:1-102
  wire signed [63:0] t;
  wire signed [63:0] result_3;
  reg signed [63:0] result_4 = (64'sd0);
  wire  c$app_arg;
  // sliding_window_high_freq.hs:261:1-94
  wire  eta_0;
  // sliding_window_high_freq.hs:261:1-94
  reg signed [63:0] out = (64'sd0);
  wire signed [63:0] result_5;
  wire signed [63:0] x;
  // sliding_window_high_freq.hs:221:1-145
  wire  enB;
  // sliding_window_high_freq.hs:221:1-145
  wire  enA;
  // sliding_window_high_freq.hs:270:1-117
  wire [255:0] c$t_app_arg;
  // sliding_window_high_freq.hs:270:1-117
  reg [127:0] window = {64'sd0,   64'sd0};
  wire [127:0] result_6;
  wire [127:0] result_7;
  wire [127:0] result_8;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] value;
  // sliding_window_high_freq.hs:270:1-117
  wire  c$t_case_alt;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] x_0;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] \c0# ;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] x1;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] x1_0;
  // sliding_window_high_freq.hs:270:1-117
  wire signed [63:0] cyclesBefore;
  // sliding_window_high_freq.hs:221:1-145
  wire [128:0] inputData;
  // sliding_window_high_freq.hs:221:1-145
  wire  c$winX4B_app_arg;
  // sliding_window_high_freq.hs:203:9-44
  wire  eta_1;
  wire [196:0] result_9;
  wire  result_10;
  wire  result_11;
  // sliding_window_high_freq.hs:179:1-142
  wire  b;
  wire [128:0] result_12;
  // sliding_window_high_freq.hs:179:1-142
  wire [128:0] t_0;
  // sliding_window_high_freq.hs:179:1-142
  reg [128:0] sustainedInput = {64'sd0,   1'b0,   64'sd0};
  wire  result_13;
  // sliding_window_high_freq.hs:179:1-142
  wire  t_1;
  // sliding_window_high_freq.hs:179:1-142
  wire  newX;
  // sliding_window_high_freq.hs:179:1-142
  reg  enA_0 = 1'b0;
  // sliding_window_high_freq.hs:179:1-142
  wire signed [63:0] waitedX;
  // sliding_window_high_freq.hs:179:1-142
  wire [64:0] xData;
  // sliding_window_high_freq.hs:179:1-142
  wire  qPopValid;
  wire  result_14;
  // sliding_window_high_freq.hs:179:1-142
  wire  b_0;
  // sliding_window_high_freq.hs:179:1-142
  reg  enB_0 = 1'b0;
  // sliding_window_high_freq.hs:179:1-142
  wire  c$timerB_app_arg;
  // sliding_window_high_freq.hs:34:1-72
  wire  eta_2;
  wire signed [63:0] result_15;
  wire signed [63:0] x_1;
  reg signed [63:0] result_16 = (64'sd2000);
  // sliding_window_high_freq.hs:179:1-142
  wire  c$timerB_app_arg_0;
  // sliding_window_high_freq.hs:179:1-142
  reg  c$stage_case_alt;
  // sliding_window_high_freq.hs:179:1-142
  wire signed [63:0] x_2;
  // sliding_window_high_freq.hs:179:1-142
  reg signed [63:0] stage = (64'sd0);
  // sliding_window_high_freq.hs:179:1-142
  wire signed [63:0] c$stage_app_arg;
  // sliding_window_high_freq.hs:44:1-64
  reg signed [63:0] s = (64'sd0);
  // sliding_window_high_freq.hs:44:1-64
  wire  b_1;
  wire signed [63:0] result_17;
  wire signed [63:0] x_3;
  wire [130:0] result_18;
  // sliding_window_high_freq.hs:68:1-78
  reg [128:0] ds = {{64'sd0,   1'b0},   -64'sd1};
  reg  c$app_arg_0 = 1'b0;
  wire  c$case_alt;
  reg  c$case_alt_0;
  reg  c$app_arg_1 = 1'b0;
  wire  c$case_alt_1;
  // sliding_window_high_freq.hs:68:1-78
  wire [128:0] c$ds_case_alt;
  // sliding_window_high_freq.hs:68:1-78
  reg [128:0] c$ds_case_alt_0;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_1;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$ds_case_scrut;
  // sliding_window_high_freq.hs:68:1-78
  wire [64:0] c$ds_app_arg;
  // sliding_window_high_freq.hs:68:1-78
  reg [383:0] \wait  = {64'sd0,   64'sd0,   64'sd0,   64'sd0,   64'sd0,   64'sd0};
  // sliding_window_high_freq.hs:68:1-78
  wire [383:0] c$wait_case_alt;
  // sliding_window_high_freq.hs:68:1-78
  wire [1547:0] c$wait_app_arg;
  // sliding_window_high_freq.hs:68:1-78
  wire [1151:0] c$wait_app_arg_0;
  // sliding_window_high_freq.hs:68:1-78
  wire [767:0] c$wait_app_arg_1;
  // sliding_window_high_freq.hs:68:1-78
  reg [389:0] buffer = {{64'sd0,   1'b0},   {64'sd0,   1'b0},   {64'sd0,   1'b0},   {64'sd0,   1'b0},
 {64'sd0,   1'b0},   {64'sd0,   1'b0}};
  // sliding_window_high_freq.hs:68:1-78
  wire [389:0] c$buffer_case_alt;
  // sliding_window_high_freq.hs:68:1-78
  wire [389:0] c$buffer_case_alt_0;
  // sliding_window_high_freq.hs:68:1-78
  reg signed [63:0] cursor = (64'sd0);
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$cursor_case_alt;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$cursor_case_alt_0;
  // sliding_window_high_freq.hs:68:1-78
  reg signed [63:0] c$cursor_case_alt_1;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$cursor_case_alt_2;
  // sliding_window_high_freq.hs:68:1-78
  wire  c$cursor_case_scrut;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x_4;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$cursor_case_alt_3;
  // sliding_window_high_freq.hs:68:1-78
  reg signed [63:0] c$cursor_case_alt_4;
  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] c$cursor_case_alt_5;
  // sliding_window_high_freq.hs:157:1-188
  wire  qPop;
  // sliding_window_high_freq.hs:157:1-188
  wire  qPush;
  wire [64:0] input0;
  wire [127:0] c$t_app_arg_res;
  wire signed [63:0] c$tte_rhs_0;
  wire signed [63:0] x_projection_4;
  wire [395:0] c$vec1;
  wire [383:0] c$wait_app_arg_res;
  wire [383:0] c$vec1_0;
  wire [454:0] c$buffer_case_alt_sel_alt_t_1;
  wire signed [63:0] c$tte_rhs_4;
  wire [584:0] result;
  wire [454:0] result_0;
  wire [64:0] result_0_5;
  wire [127:0] result_0_11_4;
  wire [129:0] result_1;
  wire [64:0] result_1_0;
  wire [64:0] result_1_1;

  assign input0 = {input0_0,   input0_1};

  assign result_2 = {{enA,   enB,   s,
                      $signed(result_9[196:133]),   window},
                     result_9[132:132],   {{out,
                                            c$app_arg & enA},   {result_4,
                                                                 c$app_arg & enB}}};

  assign eta = (s == (64'sd3)) & enB;

  wire [127:0] vec;
  wire signed [63:0] acc_1_0;
  wire signed [63:0] acc_1;
  wire signed [63:0] acc_2;
  assign t = acc_1_0;

  assign vec = window;

  assign acc_1 = $signed(vec[127:64]);

  assign acc_2 = $signed(vec[63:0]);

  wire signed [63:0] x_5;
  wire signed [63:0] y;
  wire signed [63:0] c$case_alt_2;
  assign acc_1_0 = c$case_alt_2;

  assign x_5 = acc_1;

  assign y = acc_2;

  assign c$case_alt_2 = (x_5 + y);





  assign result_3 = eta ? t : result_4;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_4_register
    if ( rst) begin
      result_4 <= (64'sd0);
    end else if (en) begin
      result_4 <= result_3;
    end
  end
  // register end

  assign c$app_arg = s == (64'sd4);

  assign eta_0 = c$winX4B_app_arg & enA;

  // register begin
  always @(posedge clk or  posedge  rst) begin : out_register
    if ( rst) begin
      out <= (64'sd0);
    end else if (en) begin
      out <= result_5;
    end
  end
  // register end

  assign result_5 = eta_0 ? ((x * 64'sd10)) : out;

  assign x = $signed(inputData[128:65]);

  assign enB = result_9[0:0];

  assign enA = result_9[1:1];

  wire signed [63:0] iterateI_ho1_0_arg0;
  wire signed [63:0] iterateI_ho1_0_res;
  assign iterateI_ho1_0_arg0 = (64'sd0);

  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_2;
  wire signed [63:0] c$case_alt_3;
  assign iterateI_ho1_0_res = c$case_alt_3;

  assign x1_2 = iterateI_ho1_0_arg0;

  assign c$case_alt_3 = (x1_2 + 64'sd1);



  assign c$t_app_arg_res = {(64'sd0),
                            iterateI_ho1_0_res};



  // zipWith start
  genvar i;
  generate
  for (i = 0; i < 2; i = i + 1) begin : zipWith
    wire signed [63:0] zipWith_in1;
    assign zipWith_in1 = c$t_app_arg_res[i*64+:64];
    wire signed [63:0] zipWith_in2;
    assign zipWith_in2 = window[i*64+:64];
    wire [127:0] c$n;
    assign c$n = {zipWith_in1,   zipWith_in2};


    assign c$t_app_arg[i*128+:128] = c$n;
  end
  endgenerate
  // zipWith end

  // register begin
  always @(posedge clk or  posedge  rst) begin : window_register
    if ( rst) begin
      window <= {64'sd0,   64'sd0};
    end else if (en) begin
      window <= result_6;
    end
  end
  // register end

  assign result_6 = c$winX4B_app_arg ? result_7 : window;

  assign result_7 = ((~ inputData[64:64]) | c$t_case_alt) ? window : result_8;

  // map begin
  genvar i_0;
  generate
  for (i_0=0; i_0 < 2; i_0 = i_0 + 1) begin : map
    wire [127:0] map_in;
    assign map_in = c$t_app_arg[i_0*128+:128];
    wire signed [63:0] map_out;
    // sliding_window_high_freq.hs:270:1-117
    wire signed [63:0] indx;
    // sliding_window_high_freq.hs:270:1-117
    wire signed [63:0] v;
    // sliding_window_high_freq.hs:270:1-117
    wire signed [63:0] x_7;
    // sliding_window_high_freq.hs:270:1-117
    wire signed [63:0] y_1;
    wire signed [63:0] c$case_alt_4;
    wire  c$case_scrut;
    wire signed [63:0] x_8;
    wire signed [63:0] y_2;
    wire signed [63:0] y_projection_0;
    wire signed [63:0] c$tte_rhs;
    assign map_out = c$case_alt_4;

    assign indx = $signed(map_in[127:64]);

    assign v = $signed(map_in[63:0]);

    assign x_7 = indx;

    assign y_projection_0 = (64'sd1 - x_0);

    assign y_1 = y_projection_0;

    assign c$case_alt_4 = c$case_scrut ? ((x_8 + y_2)) : v;

    assign c$tte_rhs = (x_7 == y_1) ? 64'sd1 : 64'sd0;

    assign c$case_scrut = c$tte_rhs[0];

    assign x_8 = v;

    assign y_2 = value;


    assign result_8[i_0*64+:64] = map_out;
  end
  endgenerate
  // map end

  assign value = $signed(inputData[128:65]);

  assign c$tte_rhs_0 = (x_0 >= 64'sd2) ? 64'sd1 : 64'sd0;

  assign c$t_case_alt = c$tte_rhs_0[0];

  assign x_projection_4 = (((x1 + \c0# ) / 64'sd25000) - \c0# );

  assign x_0 = x_projection_4;

  assign \c0#  = (x1 < 64'sd0) ? 64'sd1 : 64'sd0;

  assign x1 = x1_0 * 64'sd2000;

  assign x1_0 = cyclesBefore;

  assign cyclesBefore = $signed(inputData[63:0]);

  assign inputData = result_9[130:2];

  assign c$winX4B_app_arg = s == (64'sd2);

  assign eta_1 = (s == (64'sd0)) | (s == (64'sd1));

  assign result_9 = {result_16,   {result_11,
                                   result_10},   sustainedInput,   {enA_0,
                                                                    enB_0}};

  assign result_10 = b_0 ? 1'b1 : 1'b0;

  assign result_11 = b ? 1'b1 : 1'b0;

  assign b = eta_1 & (stage == (64'sd0));

  assign result_12 = b_0 ? t_0 : sustainedInput;

  assign t_0 = {$signed(xData[64:1]),
                newX & qPopValid,   waitedX};

  // register begin
  always @(posedge clk or  posedge  rst) begin : sustainedInput_register
    if ( rst) begin
      sustainedInput <= {64'sd0,   1'b0,   64'sd0};
    end else if (en) begin
      sustainedInput <= result_12;
    end
  end
  // register end

  assign result_13 = b_0 ? t_1 : enA_0;

  assign t_1 = qPopValid & newX;

  assign newX = xData[0:0];

  // register begin
  always @(posedge clk or  posedge  rst) begin : enA_0_register
    if ( rst) begin
      enA_0 <= 1'b0;
    end else if (en) begin
      enA_0 <= result_13;
    end
  end
  // register end

  assign waitedX = $signed(result_18[63:0]);

  assign xData = result_18[128:64];

  assign qPopValid = result_18[129:129];

  assign result_14 = b_0 ? c$timerB_app_arg : enB_0;

  assign b_0 = eta_1 & c$timerB_app_arg_0;

  // register begin
  always @(posedge clk or  posedge  rst) begin : enB_0_register
    if ( rst) begin
      enB_0 <= 1'b0;
    end else if (en) begin
      enB_0 <= result_14;
    end
  end
  // register end

  assign c$timerB_app_arg = result_16 >= (64'sd25000);

  assign eta_2 = eta_1 & (c$timerB_app_arg_0 & c$timerB_app_arg);

  assign result_15 = eta_2 ? (64'sd2000) : ((x_1 + 64'sd2000));

  assign x_1 = result_16;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_16_register
    if ( rst) begin
      result_16 <= (64'sd2000);
    end else if (en) begin
      result_16 <= result_15;
    end
  end
  // register end

  assign c$timerB_app_arg_0 = stage == (64'sd1);

  always @(*) begin
    case(x_2)
      64'sd1 : c$stage_case_alt = 1'b1;
      default : c$stage_case_alt = 1'b0;
    endcase
  end

  assign x_2 = stage;

  // register begin
  always @(posedge clk or  posedge  rst) begin : stage_register
    if ( rst) begin
      stage <= (64'sd0);
    end else if (en) begin
      stage <= c$stage_app_arg;
    end
  end
  // register end

  assign c$stage_app_arg = ((~ eta_1) | c$stage_case_alt) ? (64'sd0) : (64'sd1);

  // register begin
  always @(posedge clk or  posedge  rst) begin : s_register
    if ( rst) begin
      s <= (64'sd0);
    end else if (en) begin
      s <= result_17;
    end
  end
  // register end

  assign b_1 = s == (64'sd4);

  assign result_17 = b_1 ? (64'sd0) : ((x_3 + 64'sd1));

  assign x_3 = s;

  assign result_18 = {c$app_arg_1,   c$app_arg_0,
                      ds[128:64],   $signed(ds[63:0])};

  // register begin
  always @(posedge clk or  posedge  rst) begin : ds_register
    if ( rst) begin
      ds <= {{64'sd0,   1'b0},   -64'sd1};
    end else if (en) begin
      ds <= c$ds_case_alt;
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$app_arg_0_register
    if ( rst) begin
      c$app_arg_0 <= 1'b0;
    end else if (en) begin
      c$app_arg_0 <= c$case_alt;
    end
  end
  // register end

  assign c$case_alt = qPop ? c$case_alt_0 : 1'b0;

  always @(*) begin
    case(x_4)
      64'sd0 : c$case_alt_0 = 1'b0;
      default : c$case_alt_0 = 1'b1;
    endcase
  end

  // register begin
  always @(posedge clk or  posedge  rst) begin : c$app_arg_1_register
    if ( rst) begin
      c$app_arg_1 <= 1'b0;
    end else if (en) begin
      c$app_arg_1 <= c$case_alt_1;
    end
  end
  // register end

  assign c$case_alt_1 = qPush ? c$cursor_case_scrut : 1'b0;

  assign c$ds_case_alt = qPop ? c$ds_case_alt_0 : {{64'sd0,
                                                    1'b0},   -64'sd1};

  always @(*) begin
    case(x_4)
      64'sd0 : c$ds_case_alt_0 = {{64'sd0,   1'b0},
                                  -64'sd1};
      default : c$ds_case_alt_0 = {c$ds_app_arg,
                                   (x1_1 + 64'sd1)};
    endcase
  end

  assign x1_1 = c$ds_case_scrut;

  // index begin
  wire signed [63:0] vecArray [0:6-1];
  genvar i_1;
  generate
  for (i_1=0; i_1 < 6; i_1=i_1+1) begin : mk_array
    assign vecArray[(6-1)-i_1] = \wait [i_1*64+:64];
  end
  endgenerate
  assign c$ds_case_scrut = vecArray[c$cursor_case_alt_5];
  // index end

  // index begin
  wire [64:0] vecArray_0 [0:6-1];
  genvar i_2;
  generate
  for (i_2=0; i_2 < 6; i_2=i_2+1) begin : mk_array_0
    assign vecArray_0[(6-1)-i_2] = buffer[i_2*65+:65];
  end
  endgenerate
  assign c$ds_app_arg = vecArray_0[c$cursor_case_alt_5];
  // index end

  // register begin
  always @(posedge clk or  posedge  rst) begin : wait_register
    if ( rst) begin
      \wait  <= {64'sd0,   64'sd0,   64'sd0,   64'sd0,   64'sd0,   64'sd0};
    end else if (en) begin
      \wait  <= c$wait_case_alt;
    end
  end
  // register end

  // map begin
  genvar i_3;
  generate
  for (i_3=0; i_3 < 6; i_3 = i_3 + 1) begin : map_0
    wire [257:0] map_in_0;
    assign map_in_0 = c$wait_app_arg[i_3*258+:258];
    wire signed [63:0] map_out_0;
    wire signed [63:0] c$case_alt_8;
    // sliding_window_high_freq.hs:68:1-78
    wire  push1;
    wire signed [63:0] c$case_alt_9;
    wire signed [63:0] c$case_alt_10;
    // sliding_window_high_freq.hs:68:1-78
    wire  pop1;
    reg signed [63:0] c$case_alt_11;
    wire signed [63:0] c$case_alt_12;
    reg signed [63:0] c$case_alt_13;
    wire signed [63:0] c$case_alt_14;
    wire  c$case_scrut_0;
    wire signed [63:0] c$case_alt_15;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] x1_3;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] valToLeft;
    wire signed [63:0] c$case_alt_16;
    wire  c$case_scrut_1;
    wire signed [63:0] c$case_alt_17;
    wire  c$case_scrut_2;
    wire signed [63:0] c$case_alt_18;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] x1_4;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] val;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] y_3;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] cur1;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] x_9;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] index;
    wire signed [63:0] c$tte_rhs_1;
    wire signed [63:0] c$tte_rhs_2;
    wire signed [63:0] c$tte_rhs_3;
    assign map_out_0 = c$case_alt_8;

    assign c$case_alt_8 = push1 ? c$case_alt_9 : c$case_alt_10;

    assign push1 = map_in_0[1:1];

    assign c$case_alt_9 = pop1 ? c$case_alt_11 : c$case_alt_13;

    assign c$case_alt_10 = pop1 ? c$case_alt_16 : c$case_alt_17;

    assign pop1 = map_in_0[0:0];

    always @(*) begin
      case(x_9)
        64'sd0 : c$case_alt_11 = 64'sd0;
        default : c$case_alt_11 = c$case_alt_12;
      endcase
    end

    assign c$case_alt_12 = c$case_scrut_2 ? c$case_alt_15 : (-64'sd1);

    always @(*) begin
      case(x_9)
        64'sd0 : c$case_alt_13 = 64'sd0;
        default : c$case_alt_13 = c$case_alt_14;
      endcase
    end

    assign c$case_alt_14 = c$case_scrut_0 ? c$case_alt_15 : (-64'sd1);

    assign c$tte_rhs_1 = (x_9 <= y_3) ? 64'sd1 : 64'sd0;

    assign c$case_scrut_0 = c$tte_rhs_1[0];

    assign c$case_alt_15 = (x1_3 + 64'sd1);

    assign x1_3 = valToLeft;

    assign valToLeft = $signed(map_in_0[257:194]);

    assign c$case_alt_16 = c$case_scrut_1 ? c$case_alt_18 : (-64'sd1);

    assign c$tte_rhs_2 = (x_9 < (y_3 - 64'sd1)) ? 64'sd1 : 64'sd0;

    assign c$case_scrut_1 = c$tte_rhs_2[0];

    assign c$case_alt_17 = c$case_scrut_2 ? c$case_alt_18 : (-64'sd1);

    assign c$tte_rhs_3 = (x_9 < y_3) ? 64'sd1 : 64'sd0;

    assign c$case_scrut_2 = c$tte_rhs_3[0];

    assign c$case_alt_18 = (x1_4 + 64'sd1);

    assign x1_4 = val;

    assign val = $signed(map_in_0[193:130]);

    assign y_3 = cur1;

    assign cur1 = $signed(map_in_0[65:2]);

    assign x_9 = index;

    assign index = $signed(map_in_0[129:66]);


    assign c$wait_case_alt[i_3*64+:64] = map_out_0;
  end
  endgenerate
  // map end

  assign c$vec1 = ({6 {{qPush,   qPop,   cursor}}});

  // zipWith start
  genvar i_5;
  generate
  for (i_5 = 0; i_5 < 6; i_5 = i_5 + 1) begin : zipWith_0
    wire [65:0] zipWith_in1_0;
    assign zipWith_in1_0 = c$vec1[i_5*66+:66];
    wire [191:0] zipWith_in2_0;
    assign zipWith_in2_0 = c$wait_app_arg_0[i_5*192+:192];
    wire [257:0] c$n_0;
    // sliding_window_high_freq.hs:68:1-78
    wire  psh;
    // sliding_window_high_freq.hs:68:1-78
    wire  pp;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] c;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] i_4;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] valToLeft_1;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] val_1;
    wire [257:0] c$case_alt_19;
    assign c$n_0 = c$case_alt_19;

    assign psh = zipWith_in1_0[65:65];

    assign pp = zipWith_in1_0[64:64];

    assign c = $signed(zipWith_in1_0[63:0]);

    assign i_4 = $signed(zipWith_in2_0[191:128]);

    assign valToLeft_1 = $signed(zipWith_in2_0[127:64]);

    assign val_1 = $signed(zipWith_in2_0[63:0]);

    assign c$case_alt_19 = {valToLeft_1,   val_1,
                            i_4,   c,   psh,   pp};


    assign c$wait_app_arg[i_5*258+:258] = c$n_0;
  end
  endgenerate
  // zipWith end

  wire signed [63:0] iterateI_ho1_0_arg0_0;
  wire signed [63:0] iterateI_ho1_0_res_0;
  wire signed [63:0] iterateI_ho1_1_res;
  wire signed [63:0] iterateI_ho1_2_res;
  wire signed [63:0] iterateI_ho1_3_res;
  wire signed [63:0] iterateI_ho1_4_res;
  assign iterateI_ho1_0_arg0_0 = (64'sd0);

  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_5;
  wire signed [63:0] c$case_alt_20;
  assign iterateI_ho1_0_res_0 = c$case_alt_20;

  assign x1_5 = iterateI_ho1_0_arg0_0;

  assign c$case_alt_20 = (x1_5 + 64'sd1);



  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_6;
  wire signed [63:0] c$case_alt_21;
  assign iterateI_ho1_1_res = c$case_alt_21;

  assign x1_6 = iterateI_ho1_0_res_0;

  assign c$case_alt_21 = (x1_6 + 64'sd1);



  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_7;
  wire signed [63:0] c$case_alt_22;
  assign iterateI_ho1_2_res = c$case_alt_22;

  assign x1_7 = iterateI_ho1_1_res;

  assign c$case_alt_22 = (x1_7 + 64'sd1);



  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_8;
  wire signed [63:0] c$case_alt_23;
  assign iterateI_ho1_3_res = c$case_alt_23;

  assign x1_8 = iterateI_ho1_2_res;

  assign c$case_alt_23 = (x1_8 + 64'sd1);



  // sliding_window_high_freq.hs:68:1-78
  wire signed [63:0] x1_9;
  wire signed [63:0] c$case_alt_24;
  assign iterateI_ho1_4_res = c$case_alt_24;

  assign x1_9 = iterateI_ho1_3_res;

  assign c$case_alt_24 = (x1_9 + 64'sd1);



  assign c$wait_app_arg_res = {(64'sd0),
                               iterateI_ho1_0_res_0,   iterateI_ho1_1_res,
                               iterateI_ho1_2_res,   iterateI_ho1_3_res,
                               iterateI_ho1_4_res};



  // zipWith start
  genvar i_6;
  generate
  for (i_6 = 0; i_6 < 6; i_6 = i_6 + 1) begin : zipWith_1
    wire signed [63:0] zipWith_in1_1;
    assign zipWith_in1_1 = c$wait_app_arg_res[i_6*64+:64];
    wire [127:0] zipWith_in2_1;
    assign zipWith_in2_1 = c$wait_app_arg_1[i_6*128+:128];
    wire [191:0] c$n_1;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] b1;
    // sliding_window_high_freq.hs:68:1-78
    wire signed [63:0] c1;
    wire [191:0] c$case_alt_25;
    assign c$n_1 = c$case_alt_25;

    assign b1 = $signed(zipWith_in2_1[127:64]);

    assign c1 = $signed(zipWith_in2_1[63:0]);

    assign c$case_alt_25 = {zipWith_in1_1,   b1,
                            c1};


    assign c$wait_app_arg_0[i_6*192+:192] = c$n_1;
  end
  endgenerate
  // zipWith end

  assign c$vec1_0 = ({64'sd0,(\wait [384-1 : 64])});

  // zipWith start
  genvar i_7;
  generate
  for (i_7 = 0; i_7 < 6; i_7 = i_7 + 1) begin : zipWith_2
    wire signed [63:0] zipWith_in1_2;
    assign zipWith_in1_2 = c$vec1_0[i_7*64+:64];
    wire signed [63:0] zipWith_in2_2;
    assign zipWith_in2_2 = \wait [i_7*64+:64];
    wire [127:0] c$n_2;
    assign c$n_2 = {zipWith_in1_2,   zipWith_in2_2};


    assign c$wait_app_arg_1[i_7*128+:128] = c$n_2;
  end
  endgenerate
  // zipWith end

  // register begin
  always @(posedge clk or  posedge  rst) begin : buffer_register
    if ( rst) begin
      buffer <= {{64'sd0,   1'b0},   {64'sd0,   1'b0},   {64'sd0,   1'b0},   {64'sd0,   1'b0},
   {64'sd0,   1'b0},   {64'sd0,   1'b0}};
    end else if (en) begin
      buffer <= c$buffer_case_alt;
    end
  end
  // register end

  assign c$buffer_case_alt = qPush ? c$buffer_case_alt_0 : buffer;

  assign c$buffer_case_alt_sel_alt_t_1 = ({input0,buffer});

  assign c$buffer_case_alt_0 = c$cursor_case_scrut ? c$buffer_case_alt_sel_alt_t_1[454:65] : buffer;

  // register begin
  always @(posedge clk or  posedge  rst) begin : cursor_register
    if ( rst) begin
      cursor <= (64'sd0);
    end else if (en) begin
      cursor <= c$cursor_case_alt;
    end
  end
  // register end

  assign c$cursor_case_alt = qPush ? c$cursor_case_alt_0 : c$cursor_case_alt_3;

  assign c$cursor_case_alt_0 = qPop ? c$cursor_case_alt_1 : c$cursor_case_alt_2;

  always @(*) begin
    case(x_4)
      64'sd0 : c$cursor_case_alt_1 = 64'sd1;
      default : c$cursor_case_alt_1 = cursor;
    endcase
  end

  assign c$cursor_case_alt_2 = c$cursor_case_scrut ? ((x_4 + 64'sd1)) : cursor;

  assign c$tte_rhs_4 = (x_4 != 64'sd6) ? 64'sd1 : 64'sd0;

  assign c$cursor_case_scrut = c$tte_rhs_4[0];

  assign x_4 = cursor;

  assign c$cursor_case_alt_3 = qPop ? c$cursor_case_alt_4 : cursor;

  always @(*) begin
    case(x_4)
      64'sd0 : c$cursor_case_alt_4 = 64'sd0;
      default : c$cursor_case_alt_4 = c$cursor_case_alt_5;
    endcase
  end

  assign c$cursor_case_alt_5 = (x_4 - 64'sd1);

  assign result = {{qPush,   qPop,
                    $signed(input0[64:1]),   result_18[130:130],
                    result_18[129:129],   result_18[128:64],
                    $signed(result_18[63:0]),   result_2[388:388],
                    result_2[387:387],
                    $signed(result_2[386:323]),
                    $signed(result_2[322:259]),
                    result_2[258:131]},   result_2[129:0]};

  assign qPop = result_2[130:130];

  assign qPush = input0[0:0];

  assign result_0 = result[584:130];

  assign result_1 = result[129:0];

  assign result_0_0 = result_0[454:454];

  assign result_0_1 = result_0[453:453];

  assign result_0_2 = $signed(result_0[452:389]);

  assign result_0_3 = result_0[388:388];

  assign result_0_4 = result_0[387:387];

  assign result_0_5 = result_0[386:322];

  assign result_0_6 = $signed(result_0[321:258]);

  assign result_0_7 = result_0[257:257];

  assign result_0_8 = result_0[256:256];

  assign result_0_9 = $signed(result_0[255:192]);

  assign result_0_10 = $signed(result_0[191:128]);

  assign result_0_11_4 = result_0[127:0];

  assign result_0_5_0 = $signed(result_0_5[64:1]);

  assign result_0_5_1 = result_0_5[0:0];

  assign result_0_11_0 = $signed(result_0_11_4[127:64]);

  assign result_0_11_1 = $signed(result_0_11_4[63:0]);

  assign result_1_0 = result_1[129:65];

  assign result_1_1 = result_1[64:0];

  assign result_1_0_0 = $signed(result_1_0[64:1]);

  assign result_1_0_1 = result_1_0[0:0];

  assign result_1_1_0 = $signed(result_1_1[64:1]);

  assign result_1_1_1 = result_1_1[0:0];


endmodule

