/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input signed [63:0] a
    , input signed [63:0] b

      // Outputs
    , output wire  result
    );
  // add_streams.hs:11:1-8
  wire signed [63:0] eta;

  assign eta = a + b;

  assign result = eta > 64'sd2;


endmodule

