/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  eta // clock
    , input  eta1 // reset
    , input  eta2 // enable
    , input [31:0] eta_0

      // Outputs
    , output wire [31:0] result
    );
  // mixed.hs:10:1-80
  reg [31:0] counterSignal = 32'd0;
  reg [31:0] result_1 = 32'd0;
  // mixed.hs:10:1-80
  wire  b;
  // mixed.hs:10:1-80
  wire [31:0] t;
  wire [31:0] result_2;

  // register begin
  always @(posedge eta or  posedge  eta1) begin : counterSignal_register
    if ( eta1) begin
      counterSignal <= 32'd0;
    end else if (eta2) begin
      counterSignal <= result_2;
    end
  end
  // register end

  // register begin
  always @(posedge eta or  posedge  eta1) begin : result_1_register
    if ( eta1) begin
      result_1 <= 32'd0;
    end else if (eta2) begin
      result_1 <= counterSignal;
    end
  end
  // register end

  assign b = counterSignal < (eta_0 - 32'd1);

  assign t = counterSignal + 32'd1;

  assign result_2 = b ? t : 32'd0;

  assign result = result_1;


endmodule

