/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input signed [63:0] input0_0
    , input  input0_1

      // Outputs
    , output wire  result_0
    , output wire signed [63:0] result_1_0
    , output wire  result_1_1
    , output wire  result_1_2
    , output wire  result_1_3
    , output wire signed [63:0] result_1_4
    , output wire signed [63:0] result_2_0
    , output wire signed [63:0] result_2_1_0
    , output wire  result_2_1_1
    , output wire signed [63:0] result_2_2_0
    , output wire  result_2_2_1
    , output wire signed [63:0] result_2_3_0
    , output wire  result_2_3_1
    );
  wire [258:0] result_3;
  // different_frequencies/different_frequencies.hs:124:1-104
  wire  eta;
  wire signed [63:0] result_4;
  wire signed [63:0] x;
  wire signed [63:0] y;
  reg signed [63:0] result_5 = 64'sd10;
  // different_frequencies/different_frequencies.hs:112:1-96
  wire  eta_0;
  wire signed [63:0] result_6;
  reg signed [63:0] result_7 = 64'sd10;
  // different_frequencies/different_frequencies.hs:118:1-96
  wire  eta_1;
  wire signed [63:0] result_8;
  wire signed [63:0] result_9;
  reg signed [63:0] result_10 = 64'sd10;
  reg signed [63:0] result_11 = 64'sd10;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire signed [63:0] a;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire  c$outC_app_arg;
  wire [2:0] result_12;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire  b;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire  enB;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire  enC;
  // different_frequencies/different_frequencies.hs:96:1-158
  wire  \enD ;
  reg signed [63:0] c$app_arg = 64'sd0;
  // different_frequencies/different_frequencies.hs:38:1-64
  reg signed [63:0] s = 64'sd0;
  // different_frequencies/different_frequencies.hs:38:1-64
  wire  b_0;
  wire signed [63:0] result_13;
  wire signed [63:0] x_0;
  reg [130:0] result_14 = {64'sd0,   1'b0,   1'b0,   1'b0,   64'sd0};
  wire [130:0] result_15;
  wire  result_16;
  // different_frequencies/different_frequencies.hs:63:1-123
  wire  b_1;
  wire signed [63:0] result_17;
  wire signed [63:0] x_1;
  reg signed [63:0] result_18 = 64'sd0;
  wire  result_19;
  // different_frequencies/different_frequencies.hs:63:1-123
  wire  b_2;
  wire signed [63:0] result_20;
  wire signed [63:0] x_2;
  reg signed [63:0] result_21 = 64'sd0;
  wire  result_22;
  // different_frequencies/different_frequencies.hs:63:1-123
  wire  b_3;
  wire signed [63:0] result_23;
  wire signed [63:0] x_3;
  reg signed [63:0] result_24 = 64'sd0;
  // different_frequencies/different_frequencies.hs:14:1-73
  wire  b_4;
  wire  result_25;
  // different_frequencies/different_frequencies.hs:21:5-74
  wire  b_5;
  // different_frequencies/different_frequencies.hs:21:5-74
  wire signed [63:0] t;
  wire signed [63:0] result_26;
  reg signed [63:0] result_27 = 64'sd0;
  reg  result_28 = 1'b0;
  wire [64:0] input0;
  wire [390:0] result;
  wire [130:0] result_1_5;
  wire [258:0] result_2;
  wire [64:0] result_2_1;
  wire [64:0] result_2_2;
  wire [64:0] result_2_3;

  assign input0 = {input0_0,   input0_1};

  assign result = {result_28,   result_14,
                   result_3};

  assign result_3 = {c$app_arg,   {result_7,
                                   result_12[2:2]},   {result_11,
                                                       result_12[1:1]},   {result_5,
                                                                           result_12[0:0]}};

  assign eta = (c$app_arg == 64'sd2) & \enD ;

  assign result_4 = eta ? (x + y) : result_5;

  assign x = result_7;

  assign y = result_11;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_5_register
    if ( rst) begin
      result_5 <= 64'sd10;
    end else if (en) begin
      result_5 <= result_4;
    end
  end
  // register end

  assign eta_0 = c$outC_app_arg & enB;

  assign result_6 = eta_0 ? a : result_7;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_7_register
    if ( rst) begin
      result_7 <= 64'sd10;
    end else if (en) begin
      result_7 <= result_6;
    end
  end
  // register end

  assign eta_1 = c$outC_app_arg & enC;

  assign result_8 = eta_1 ? a : result_10;

  assign result_9 = eta_1 ? a : result_10;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_10_register
    if ( rst) begin
      result_10 <= 64'sd10;
    end else if (en) begin
      result_10 <= result_9;
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_11_register
    if ( rst) begin
      result_11 <= 64'sd10;
    end else if (en) begin
      result_11 <= result_8;
    end
  end
  // register end

  assign a = $signed(result_14[130:67]);

  assign c$outC_app_arg = c$app_arg == 64'sd1;

  assign result_12 = b ? {enB,   enC,
                          \enD } : {1'b0,   1'b0,   1'b0};

  assign b = c$app_arg == 64'sd3;

  assign enB = result_14[66:66];

  assign enC = result_14[65:65];

  assign \enD  = result_14[64:64];

  // delay begin
  always @(posedge clk) begin : c$app_arg_delay
    if (en) begin
      c$app_arg <= s;
    end
  end
  // delay end

  // register begin
  always @(posedge clk or  posedge  rst) begin : s_register
    if ( rst) begin
      s <= 64'sd0;
    end else if (en) begin
      s <= result_13;
    end
  end
  // register end

  assign b_0 = s == 64'sd3;

  assign result_13 = b_0 ? 64'sd0 : (x_0 + 64'sd1);

  assign x_0 = s;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_14_register
    if ( rst) begin
      result_14 <= {64'sd0,   1'b0,   1'b0,   1'b0,   64'sd0};
    end else if (en) begin
      result_14 <= result_15;
    end
  end
  // register end

  assign result_15 = result_28 ? {$signed(input0[64:1]),
                                  result_16,   result_19,   result_22,
                                  result_18} : result_14;

  assign result_16 = b_1 ? 1'b1 : 1'b0;

  assign b_1 = result_18 >= 64'sd100000;

  assign result_17 = result_16 ? 64'sd0 : (x_1 + 64'sd2000);

  assign x_1 = result_18;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_18_register
    if ( rst) begin
      result_18 <= 64'sd0;
    end else if (en) begin
      result_18 <= result_17;
    end
  end
  // register end

  assign result_19 = b_2 ? 1'b1 : 1'b0;

  assign b_2 = result_21 >= 64'sd200000;

  assign result_20 = result_19 ? 64'sd0 : (x_2 + 64'sd2000);

  assign x_2 = result_21;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_21_register
    if ( rst) begin
      result_21 <= 64'sd0;
    end else if (en) begin
      result_21 <= result_20;
    end
  end
  // register end

  assign result_22 = b_3 ? 1'b1 : 1'b0;

  assign b_3 = result_24 >= 64'sd400000;

  assign result_23 = result_22 ? 64'sd0 : (x_3 + 64'sd2000);

  assign x_3 = result_24;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_24_register
    if ( rst) begin
      result_24 <= 64'sd0;
    end else if (en) begin
      result_24 <= result_23;
    end
  end
  // register end

  assign b_4 = result_27 < 64'sd2;

  assign result_25 = b_4 ? 1'b1 : 1'b0;

  assign b_5 = result_27 < 64'sd4;

  assign t = result_27 + 64'sd1;

  assign result_26 = b_5 ? t : 64'sd0;

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_27_register
    if ( rst) begin
      result_27 <= 64'sd0;
    end else if (en) begin
      result_27 <= result_26;
    end
  end
  // register end

  // register begin
  always @(posedge clk or  posedge  rst) begin : result_28_register
    if ( rst) begin
      result_28 <= 1'b0;
    end else if (en) begin
      result_28 <= result_25;
    end
  end
  // register end

  assign result_0 = result[390:390];

  assign result_1_5 = result[389:259];

  assign result_2 = result[258:0];

  assign result_1_0 = $signed(result_1_5[130:67]);

  assign result_1_1 = result_1_5[66:66];

  assign result_1_2 = result_1_5[65:65];

  assign result_1_3 = result_1_5[64:64];

  assign result_1_4 = $signed(result_1_5[63:0]);

  assign result_2_0 = $signed(result_2[258:195]);

  assign result_2_1 = result_2[194:130];

  assign result_2_2 = result_2[129:65];

  assign result_2_3 = result_2[64:0];

  assign result_2_1_0 = $signed(result_2_1[64:1]);

  assign result_2_1_1 = result_2_1[0:0];

  assign result_2_2_0 = $signed(result_2_2[64:1]);

  assign result_2_2_1 = result_2_2[0:0];

  assign result_2_3_0 = $signed(result_2_3[64:1]);

  assign result_2_3_1 = result_2_3[0:0];


endmodule

