/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.6.4. DO NOT MODIFY.
*/
`timescale 100fs/100fs
module topEntity
    ( // Inputs
      input  clk // clock
    , input  rst // reset
    , input  en // enable
    , input  to_add
    , input signed [63:0] a
    , input signed [63:0] b

      // Outputs
    , output wire  result_0
    , output wire  result_1
    );
  // add_on_condition.hs:(5,1)-(7,26)
  wire signed [63:0] t;
  // add_on_condition.hs:(5,1)-(7,26)
  wire signed [63:0] f1;
  wire signed [63:0] result_4;
  wire [1:0] result;

  assign result = {result_4 > 64'sd10,
                   result_4 < 64'sd5};

  assign t = a + b;

  assign f1 = a - b;

  assign result_4 = to_add ? t : f1;

  assign result_0 = result[1:1];

  assign result_1 = result[0:0];


endmodule

